crowdsourcing/urls.py
from django.conf.urls import url
from . import views # . = current directory

app_name = 'crowdsourcing'

urlpatterns = [
		url(r'^$', views.IndexView.as_view(), name='index'),

		url(r'caratteristiche/$', views.CaratteristicheView.as_view(), name='Caratteristiche'),

		url(r'funzionamento/$', views.FunzionamentoView.as_view(), name='Funzionamento'),

		url(r'promote/$', views.Promote.as_view(), name='Promote'),

		url(r'register/$', views.Register.as_view(), name='Register'),

		url(r'login/$', views.Login.as_view(), name='Login'),

		url(r'logout/$', views.Logout, name='Logout'),

		url(r'campaign/$', views.Campaign.as_view(), name='Campaign'),

		url(r'SignUpToCampaign/(?P<campaign_id>[0-9]+)$', views.SignUpToCampaign.as_view(), name='SignUpToCampaign'),

		url(r'task/$', views.Task.as_view(), name='Task'),

		url(r'user/$', views.User.as_view(), name='User'),
]

myProj/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
		url(r'^crowdsourcing/', include('crowdsourcing.urls')),
		url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crowdsourcing/models.py
from __future__ import unicode_literals
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils import timezone
from django.contrib.auth.models import User
from decimal import Decimal

class Worker(models.Model):
	id = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
	genre = models.CharField(max_length=1)
	birth_date = models.DateField()
	w_score = models.DecimalField(max_digits=5, decimal_places=2, default=Decimal('0.00'))
	w_trustworthiness = models.DecimalField(max_digits=4, decimal_places=2, default=Decimal('1.00'))
	banned = models.BooleanField(default=False)

	def __unicode__(self):
		name = self.id.first_name + " " +self.id.last_name + " - " + self.id.username 
		return str(self.id.id) + ": " + name 

class Campaign(models.Model):
	name = models.TextField()
	creation_date = models.DateTimeField(default=timezone.now )
	start_date = models.DateField()
	finish_date = models.DateField()
	start_signup = models.DateField()
	finish_signup = models.DateField()
	init_trustworthiness = models.DecimalField(max_digits=4, decimal_places=2)
	w_campaign = models.ManyToManyField(Worker, through='Worker_Campaign')

	def __unicode__(self):
		return str(self.id) + ": " + self.name

class Task_Status(models.Model):
	name = models.TextField()

	def __unicode__(self):
		return str(self.id) + ": " + self.name
		
class Answer_Type(models.Model):
	name = models.TextField()

	def __unicode__(self):
		return str(self.id) + ": " + self.name

class Task(models.Model):
	description = models.TextField()
	answer_type = models.ForeignKey(Answer_Type, on_delete = models.CASCADE)
	insert_date = models.DateTimeField(default = timezone.now )
	priority = models.IntegerField(default = 0)
	final_answer = models.TextField(null = True, blank = True)
	campaign = models.ForeignKey(Campaign, on_delete = models.CASCADE)
	task_status = models.ForeignKey(Task_Status, on_delete = models.CASCADE)
	current_round = models.IntegerField(null = True,blank = True)
	w_task = models.ManyToManyField(Worker, through = 'Worker_Task')

	def __unicode__(self):
		return str(self.id) + ": Task - " + self.campaign.name

class Task_Setup(models.Model):
	num_worker = models.IntegerField()
	min_trustworthiness = models.DecimalField(max_digits=4, decimal_places=2)
	consensus_threshold = models.DecimalField(max_digits=4, decimal_places=2)
	max_exec_time = models.IntegerField()
	t_task_setup = models.ManyToManyField(Task, through='Task_Task_Setup')

class Worker_Campaign(models.Model):
	worker = models.ForeignKey(Worker, on_delete=models.CASCADE)
	campaign = models.ForeignKey(Campaign, on_delete=models.CASCADE)
	c_score = models.DecimalField(max_digits=5, decimal_places=2, default=Decimal('0.00'))
	c_trustworthiness = models.DecimalField(max_digits=4, decimal_places=2, default=Decimal('1.00'))
	worker_banned = models.BooleanField(default=False)

	def __unicode__(self):
		name = self.worker.id.first_name + " - " + self.campaign.name
		return name 

class Worker_Task(models.Model):
	id = models.AutoField(primary_key=True)
	worker = models.ForeignKey(Worker, on_delete=models.CASCADE)
	task = models.ForeignKey(Task, on_delete=models.CASCADE)
	round = models.IntegerField()
	timeout = models.BooleanField(default=True)
	refused = models.BooleanField(default=False)
	timestamp_in = models.DateTimeField(default=timezone.now )
	timestamp_out = models.DateTimeField()
	answer = models.TextField(null=True,blank=True)
	current_w_trustworthiness = models.DecimalField(max_digits=4, decimal_places=2)

	def __unicode__(self):
		name = "Round " + str(self.round) + " - " + self.worker.id.username + " - Task: " + str(self.task.id)
		return name 

	class Meta:
	 unique_together = ('worker','task','round',)

class Task_Task_Setup(models.Model):
	task_setup = models.ForeignKey(Task_Setup, on_delete=models.CASCADE)
	task = models.ForeignKey(Task, on_delete=models.CASCADE)
	round = models.IntegerField()

crowdsourcing/forms.py
from django.contrib.auth.models import User

from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class UserForm(forms.ModelForm):
	first_name = forms.CharField(label='first_name',
		widget=forms.TextInput(attrs={'class': 'form-control', 'id' : 'first_name', 'placeholder' : 'First name'}))

	last_name = forms.CharField(label='last_name',
		widget=forms.TextInput(attrs={'class': 'form-control', 'id' : 'last_name', 'placeholder' : 'Last name'}))

	username =  forms.CharField(label='username',
		widget=forms.TextInput(attrs={'class': 'form-control', 'id' : 'username', 'placeholder' : 'Username'}))
	
	password =  forms.CharField(label='password',
		widget=forms.PasswordInput(attrs={'class': 'form-control', 'id' : 'password', 'placeholder' : 'Password'}))
	
	email =  forms.CharField(label='email',
		widget=forms.EmailInput(attrs={'class': 'form-control', 'id' : 'email', 'placeholder' : 'Email'}))

	class Meta:
		model = User
		fields = ('first_name', 'last_name', 'username', 'password', 'email')

class LoginForm(forms.ModelForm):

	class Meta:
		model = User
		fields = ('username', 'password')

class UploadFileForm(forms.Form):
	file = forms.FileField()

crowdsourcing/views.py
from __future__ import unicode_literals
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, models
from django.contrib.auth.models import User as UserModel, Group
from django.views.generic import View
from .models import Worker, Worker_Campaign, Task_Status, Answer_Type, Task_Setup
from .models import Campaign as CampaignModel, Task as TaskModel, Worker_Task as Worker_TaskModel, Task_Task_Setup

from .forms import UserForm, LoginForm, UploadFileForm
from datetime import datetime
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist

from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from collections import Counter

import json, string, random

class IndexView(generic.ListView):
	template_name = 'crowdsourcing/index.html'
	context_object_name = 'all_workers'

	def get_queryset(self):
		group = models.Group.objects.get(name='Workers')		
		return group.user_set.all()

	def get_context_data(self, **kwargs):

		context = super(IndexView, self).get_context_data(**kwargs)
		
		userLogged = self.request.user

		if userLogged.is_authenticated():

			if userLogged.groups.filter(name__in=['Workers']).exists():

				worker = Worker.objects.get(id=userLogged)
				campaignSignedUp = Worker_Campaign.objects.filter(worker=worker, worker_banned=False)
				campaignSignedUpID = campaignSignedUp.values('campaign_id')

				context['already_joined'] = CampaignModel.objects.filter(id__in=campaignSignedUpID)

				context['to_join'] = CampaignModel.objects.exclude(id__in=campaignSignedUpID).exclude(finish_signup__lte=datetime.now().date())

				context['score_trust'] = campaignSignedUp

		return context

class CaratteristicheView(View):
	template_name = 'crowdsourcing/caratteristiche.html'

	def get(self, request):
		return render(request, self.template_name)

class FunzionamentoView(View):
	template_name = 'crowdsourcing/funzionamento.html'

	def get(self, request):
		return render(request, self.template_name)

class Register(View):
	form_class = UserForm
	template_name = 'crowdsourcing/register.html'

	def get(self, request):
		if request.user.is_authenticated:
			return redirect('crowdsourcing:index')

		form = self.form_class(None)
		return render(request, self.template_name, {'form' : form})

	def post(self, request):
		if request.user.is_authenticated:
			return redirect('crowdsourcing:index')

		form = UserForm(request.POST)

		if form.is_valid():

			user = form.save(commit=False)
			
			first_name = form.cleaned_data['first_name']
			last_name = form.cleaned_data['last_name']
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			email = form.cleaned_data['email']
			
			if UserModel.objects.filter(email=email).exists():
				return render(request, self.template_name,
					{'form' : form, 'email' : 'A user with that email already exists.'} )

			user.set_password(user.password)
			form.save()

			g = Group.objects.get(name='Workers') 
			g.user_set.add(user)

			worker = Worker(id=user, genre=request.POST['genre'], birth_date=request.POST['birth_date'])
			worker.save()
			
			if user is not None:
				return redirect('crowdsourcing:index')

		return render(request, self.template_name, {'form' : form})

class Login(View):
	form_class = LoginForm
	template_name = 'crowdsourcing/header.html'
	
	def get(self, request):
		form = self.form_class(None)
		return redirect('crowdsourcing:index')

	def post(self, request):
		form = self.form_class(request.POST)

		username = request.POST['username']
		password = request.POST['password']
		try:
			user = UserModel.objects.get(username=username)
			if not(user.is_superuser):
				Worker.objects.get(id=user, banned=False)
		except ObjectDoesNotExist:
			messages.error(request, 'User does not exist or they were banned')
			return HttpResponseRedirect(reverse('crowdsourcing:index'))
		
		user = authenticate(username=username, password=password)
		if user is not None:
			login(request, user)
			return redirect('crowdsourcing:index')
		else:
			messages.error(request, "Your password didn't match. Please try again")
			return HttpResponseRedirect(reverse('crowdsourcing:index'))

def Logout(request):
	logout(request)
	return redirect('crowdsourcing:index')

class User(View):
	template_name = 'crowdsourcing/user.html'

	def get(self, request):
		if request.user.is_authenticated:
			userLogged = self.request.user
			worker = Worker.objects.get(id=userLogged)

			userInfo = {
				'username': userLogged.username,
				'first_name': userLogged.first_name,
				'last_name': userLogged.last_name,
				'email': userLogged.email,
				'groups': userLogged.groups.all()[0].name,
				'date_joined': userLogged.date_joined,
				'w_score': worker.w_score,
				'w_trustworthiness': worker.w_trustworthiness
			}

			return render(request, self.template_name, {'userInfo' : userInfo})

		return redirect('crowdsourcing:index')	
	
	def post(self, request):

		if request.user.is_authenticated:
			userLogged = self.request.user
			worker = Worker.objects.get(id=userLogged)

			userInfo = {
				'username': userLogged.username,
				'first_name': userLogged.first_name,
				'last_name': userLogged.last_name,
				'email': userLogged.email,
				'groups': userLogged.groups.all()[0].name,
				'date_joined': userLogged.date_joined,
				'w_score': worker.w_score,
				'w_trustworthiness': worker.w_trustworthiness
			}
	
			old_psw = request.POST['old_psw']
			new_psw = request.POST['new_psw']

			if userLogged.check_password(old_psw):
				u = UserModel.objects.get(username=userLogged.username)
				u.set_password(new_psw)
				u.save()
				return render(request, self.template_name,{'userInfo' : userInfo, 'psw_message' : 'Password changed successfully'} )
			return render(request, self.template_name,{'userInfo' : userInfo, 'psw_message' : 'Password incorrect'} )

class Promote(View):

	def get(self, request):
		return redirect('crowdsourcing:index')

	def post(self, request):
		if request.POST:
		
			for worker in request.POST.getlist('worker_list'):
				user = UserModel.objects.get(username=worker)
				p = Group.objects.get(name='Promoters')
				w = Group.objects.get(name='Workers')
				p.user_set.add(user)
				w.user_set.remove(user)

		return redirect('crowdsourcing:index')

class Campaign(View):
	form_class = UploadFileForm
	template_name = 'crowdsourcing/campaign.html'	

	def get(self, request):

		userLogged = self.request.user
		
		if userLogged.is_authenticated:
			if userLogged.groups.filter(name__in=['Workers']).exists():
				return redirect('crowdsourcing:index')

			form = self.form_class(None)
			return render(request, self.template_name, {'form' : form})

		return redirect('crowdsourcing:index')

	def post(self, request):
		fileName = settings.MEDIA_ROOT+'/tasks_' + self.request.user.username + '.json'

		def handle_uploaded_file(f):
			with open(fileName, 'wb+') as destination:
				for chunk in f.chunks():
					destination.write(chunk)

		form = UploadFileForm(request.POST, request.FILES)
		
		if form.is_valid():

			campaign = CampaignModel(name = request.POST['name'], start_date = request.POST['start_date'],
				finish_date = request.POST['finish_date'], start_signup = request.POST['start_signup'],
				finish_signup = request.POST['finish_signup'], init_trustworthiness = request.POST['init_trustworthiness'])

			campaign.save()

			handle_uploaded_file(request.FILES['file'])
			json_data = open(fileName)
			data = json.load(json_data)

			answer_type = Answer_Type.objects.get(name='loaded')
			task_status = Task_Status.objects.get(id=1)

			for item in data["tasks"]:
				description = json.dumps(item, ensure_ascii=False)
				description = description.replace('\\x', '\\u00')
				task = TaskModel(description = description, answer_type = answer_type, priority = settings.TASK_PRIORITY, campaign = campaign,
					task_status = task_status)
				task.save()

			json_data.close()

			return redirect('crowdsourcing:index')
		
		return render(request, self.template_name, {'form' : form})

class SignUpToCampaign(View):

	def get(self, request, campaign_id):
		return redirect('crowdsourcing:index')

	def post(self, request, campaign_id):
		if request.POST:
		
			SUtoCampaign = CampaignModel.objects.get(id=campaign_id)
			worker = Worker.objects.get(id=self.request.user)
			wc = Worker_Campaign(worker=worker, campaign=SUtoCampaign)
			wc.save()

		return redirect('crowdsourcing:index')

class Task(View):
	template_name = 'crowdsourcing/task.html'

	def get(self, request):
		return HttpResponseRedirect(reverse('crowdsourcing:index'))

	def post(self, request):

		if request.user.is_authenticated:
			
			userLogged = self.request.user
			worker = Worker.objects.get(id=userLogged)

			if request.POST['answer'] == 'false':
				campaign = CampaignModel.objects.get(id=request.POST['campaign'])

				campaignTasksList = TaskModel.objects.filter(campaign = request.POST['campaign']).values_list('id', flat=True)
				campaignTasksList = list(campaignTasksList)

				while True:

					if not campaignTasksList :
						messages.warning(request, 'No Task avaible for Campaign: ' + campaign.name)
						return HttpResponseRedirect(reverse('crowdsourcing:index'))

					else :
						idRandom = random.choice(campaignTasksList)

						task = TaskModel.objects.get(id=idRandom)

						task_status = Task_Status.objects.get(name='loaded')
						task_setup = Task_Setup.objects.get(id=1)
						tts = Task_Task_Setup.objects.get(task_setup = task_setup, task = task)
								
						if task.current_round is None :
							task.current_round = 1
							task.save()

						if task.task_status == task_status and task.current_round <= tts.round :

							count = Worker_TaskModel.objects.filter(task = task, round = task.current_round).count()

crowdsourcing/templates/crowdsourcing/administrator.html
{% if all_workers %}

	<form action="{% url 'crowdsourcing:Promote' %}" method="post">
		{% csrf_token %}
		<div class="form-group">
			{% for worker in all_workers %}
			<label class="custom-control custom-checkbox">
				<input type="checkbox" class="custom-control-input" name="worker_list" value="{{worker.username }}">
				<span class="custom-control-indicator"></span>
				<span class="custom-control-description">{{ worker.first_name }} {{worker.last_name }} - {{worker.username }}</span>
			</label><br>
			{% endfor %}
		</div>
		<div class="form-group">
			<button type="submit" class="btn btn-warning">Promote</button>
		</div>
	</form>

{% else %}
	<h4>No Workers to promote</h4>
{% endif %}

crowdsourcing/templates/crowdsourcing/campaign.html
{% extends 'crowdsourcing/base.html' %}

{% load crowdsourcing_extras %}

{% block main %}

<div class="jumbotron">
	<div class="container">

		<h2>Create a new Campaign</h2><br>
		<form action="{% url 'crowdsourcing:Campaign' %}" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			<div class="row">
				<div class="form-group col-md-6">
					<label class="col-form-label" for="name">Name:</label>
					<input class="form-control" id="name" type="text" name="name" >
				</div>
				<div class="form-group col-md-6">
					<label for="file">Upload JSON tasks</label><br>
					{% for field in form %}
						{{ field }}
					{% endfor %}
				</div>
				<div class="form-group col-md-6">
					<label class="col-form-label" for="start_date">Start date:</label>
					<a class="today" id="start_date_t" href="#">Today</a>
					<input class="form-control" id="start_date" type="date" name="start_date" required="">
				</div>
				<div class="form-group col-md-6">
					<label class="col-form-label" for="finish_date">Finish date:</label>
					<a class="today" id="finish_date_t" href="#">Today</a>
					<input class="form-control" id="finish_date" type="date" name="finish_date" required="">
				</div>
				<div class="form-group col-md-6">
					<label class="col-form-label" for="start_signup">Start date to sign up:</label>
					<a class="today" id="start_signup_t" href="#">Today</a>
					<input class="form-control" id="start_signup" type="date" name="start_signup" required="">
				</div>
				<div class="form-group col-md-6">
					<label class="col-form-label" for="finish_signup">Finish date to sign up:</label>
					<a class="today" id="finish_signup_t" href="#">Today</a>
					<input class="form-control" id="finish_signup" type="date" name="finish_signup" required="">
				</div>
				<div class="form-group col-md-6">
					<label class="col-form-label" for="init_trustworthiness">Initial trustworthiness</label>
					<input class="form-control" type="number" name="init_trustworthiness" step="0.01" required="" id="init_trustworthiness">
				</div>
				
				<div class="form-group col-auto">
					<label class="col-form-label"></label><br>
					<button class="btn btn-outline-success my-2 mr-sm-2" type="submit">Create</button>
					<p id="error-warning" style="display: none">Wrong date</p>
				</div>
			</div>
		</form>
	</div>
</div>
{% endblock %}

{% block javascript %}
<script type="text/javascript">

$(document).ready(function () {

	var now = new Date();

	var day = ("0" + now.getDate()).slice(-2);
	var month = ("0" + (now.getMonth() + 1)).slice(-2);

	var today = now.getFullYear()+"-"+(month)+"-"+(day) ;

	$( ".today" ).on( "click", function() {
		id = ($(this)[0].id).slice(0,-2);
		$(':input[id='+id+']').val(today);
	});

	$('form').submit(function () {
			var start_date = $('#start_date').val();
			var finish_date = $('#finish_date').val();
			var start_signup = $('#start_signup').val();
			var finish_signup = $('#finish_signup').val();

			if (start_date > finish_date || start_signup > finish_signup || finish_signup > start_date) {
					$("#error-warning").show();
					return false;
			}
	});

});

</script>
{% endblock %}

crowdsourcing/templates/crowdsourcing/header.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
	<a class="navbar-brand" href="{% url 'crowdsourcing:index' %}">Crowdsourcing</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse" id="navbar">
		<ul class="navbar-nav mr-auto">
			{% block active %}
			<li class="nav-item">
				<a class="nav-link" href="{% url 'crowdsourcing:index' %}">Home<span class="sr-only">(current)</span></a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'crowdsourcing:Caratteristiche' %}">Caratteristiche</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'crowdsourcing:Funzionamento' %}">Funzionamento</a>
			</li>
			{% endblock %}
		</ul>
		{% if request.user.is_authenticated %}
		<a href="{% url 'crowdsourcing:User' %}"><span class="badge badge-pill badge-primary mr-sm-2" style="font-size: 85%;">{{ user }}</span></a>
		<form class="form-inline my-2 my-lg-0" action="" method="post">
			<a href="{% url 'crowdsourcing:Logout' %}" class="btn btn-outline-primary my-2 my-sm-2">
				Logout
			</a>
		</form>
		{% endif %}

		{% if not request.user.is_authenticated %}
		<form class="form-inline my-2 my-lg-0" action="{% url 'crowdsourcing:Login' %}" method="post">
			{% csrf_token %}
			<input id="id_username" class="form-control mr-sm-2" type="text" name="username" required placeholder="Username" />
			<input id="id_password" class="form-control mr-sm-2" type="password" name="password" required placeholder="Password" />

			<button class="btn btn-outline-success my-2 mr-sm-2" type="submit">Login</button>
			<a href="{% url 'crowdsourcing:Register' %}" class="btn btn-outline-warning my-2 my-sm-2">Sign up</a>

		</form>
		{% endif %}
	</div>
</nav>

crowdsourcing/templates/crowdsourcing/index.html
{% extends 'crowdsourcing/base.html' %}

{% load crowdsourcing_extras %}

{% block first %}

{% if request.user|has_group:"Administrators" %}
	

		{% include 'crowdsourcing/administrator.html' %}	


{% elif request.user|has_group:"Promoters" %}


		{% include 'crowdsourcing/promoter.html' %}	


{% elif request.user|has_group:"Workers" %}


		{% include 'crowdsourcing/worker.html' %}	
	

{% endif %}


{% endblock %}

crowdsourcing/templates/crowdsourcing/promoter.html
<p><a class="btn btn-primary btn-lg" href="{% url 'crowdsourcing:Campaign' %}" role="button">Create a Campaign</a></p>

crowdsourcing/templates/crowdsourcing/worker.html
{% load crowdsourcing_extras %}

<div id="accordion" role="tablist">

	<div class="card">
		<a class="collapsed" data-toggle="collapse" href="#One" aria-expanded="false" aria-controls="One">
			<h5 class="mb-0">
				<div class="card-header" role="tab" id="headingOne">
					Campaigns you can join
				</div>
			</h5>
		</a>
		<div id="One" class="collapse" role="tabpanel" aria-labelledby="headingOne" data-parent="#accordion">
			<div class="card-body">
				{% if to_join %}

					<table class="table table-striped">
							<thead class="thead-inverse">
								<tr>
									<th>#</th>
									<th>Name</th>
									<th>Start Date</th>
									<th>Finish Date</th>
									<th>Start sign up</th>
									<th>Finish sign up</th>
									<th>Sign up</th>
								</tr>
							</thead>
							<tbody>
								{% for campaign in to_join %}
								<tr>
									
										<td scope="row">{{forloop.counter}}</th>
										<td>{{ campaign.name }}</td>
										<td>{{ campaign.start_date }}</td>
										<td>{{ campaign.finish_date }}</td>
										<td>{{ campaign.start_signup }}</td>
										<td>{{ campaign.finish_signup }}</td>
										<td>
											<form action="{% url 'crowdsourcing:SignUpToCampaign' campaign.id %}" method="post">
												{% csrf_token %}
												<div class="form-group">
													<button type="submit" class="btn btn-outline-info">Sign up</button>
												</div>
											</form>
										</td>									
								</tr>
								{% endfor %}
							</tbody>
						</table>
					
				{% else %}
					<h4>No campaigns available</h4>
				{% endif %}
			</div>
		</div>
	</div>

	<div class="card">
		<a class="collapsed" data-toggle="collapse" href="#Two" aria-expanded="false" aria-controls="Two">
			<h5 class="mb-0">
				<div class="card-header" role="tab" id="headingTwo">
					Campaigns you've already joined
				</div>
			</h5>
		</a>
		<div id="Two" class="collapse" role="tabpanel" aria-labelledby="headingTwo" data-parent="#accordion">
			<div class="card-body">
				{% if already_joined %}

					<table class="table table-striped">
							<thead class="thead-inverse">
								<tr>
									<th>#</th>
									<th>Name</th>
									<th>Start Date</th>
									<th>Finish Date</th>
									<th>Start sign up</th>
									<th>Finish sign up</th>
									<th>Sign up</th>
								</tr>
							</thead>
							<tbody>
								{% for campaign in already_joined %}
								<tr>
									
										<th scope="row">{{forloop.counter}}</th>
										<td>{{ campaign.name }}</td>
										<td>{{ campaign.start_date }}</td>
										<td>{{ campaign.finish_date }}</td>
										<td>{{ campaign.start_signup }}</td>
										<td>{{ campaign.finish_signup }}</td>
										<td>
											{% if campaign.start_date|is_future or campaign.finish_date|is_past %}
												<a href="#" class="btn btn-outline-info disabled" role="button" aria-disabled="true">Ask for a task</a>
											{% else %}
												<form action="{% url 'crowdsourcing:Task' %}" method="post">
													{% csrf_token %}
													<input type="hidden" name="answer" value="false">
													<input type="hidden" name="campaign" value="{{ campaign.id }}">
													<button class="btn btn-outline-success" type="submit">Ask for a task</button>
												</form>
											{% endif %}
										</td>
								</tr>
								{% for st in score_trust %}
									{% if campaign.id == st.id %}
										<tr>
												<td></td>
												<td><strong>Score:</strong></td>
												<td colspan="2">{{st.c_score}}</td>
												<td><strong>Trustworthiness:</strong></td>
												<td colspan="2">{{st.c_trustworthiness}}</td>
										</tr>
									{% endif %}
								{% endfor %}

							{% endfor %}
							</tbody>
						</table>
					
				{% else %}
					<h4>No campaigns available</h4>
				{% endif %}
			</div>
		</div>
	</div>

</div>